apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: node-ascii-fn
  namespace: default
spec:
  template:
    metadata:
      annotations:
#        autoscaling.knative.dev/window: 600s 
    spec:
      containers:
        - image: docker.io/gigi1982/node-ascii-fn
